version: "3"
services:
    poll:
        image: poll
        depends_on:
            - redis
        ports:
            - "5000:80"
        networks:
            - poll-tier
     redis:
        images: redis
        ports:
            - "6379:6379"
     worker:
        image: worker
        networks:
            - back-tier
     db:
        image: postgres
     result:
        image: result
        ports:
            - "5001:80"
        networks:
            - result-tier
networks:
    poll-tier:
    back-tier:
    